import React from 'react';
import { Link } from 'react-router-dom';
import Footer from '../components/Footer';

export default function Terms() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-indigo-900 to-gray-900 text-white">
      <main className="p-6 flex flex-col items-center pb-20">

      <div className="max-w-3xl space-y-6">
            <h1 className="text-4xl font-bold text-center mb-6">Terms of Use</h1>
            
            <p className="text-lg">
              Welcome to <strong>Fantasy Name Creator</strong>, a free fantasy name generation tool provided by Neoantica. By using this website, you agree to the following terms and conditions. If you do not agree with these terms, please do not use the site.
            </p>
            
            <h2 className="text-2xl font-semibold mt-6">1. Use of the Service</h2>
            <p className="text-lg">
              Fantasy Name Creator is intended for creative purposes such as worldbuilding, storytelling, TTRPG design, writing, or personal projects. You may freely use the names generated by this tool. For commercial use, attribution to Fantasy Name Creator or Neoantica is appreciated but not required.
            </p>
            
            <h2 className="text-2xl font-semibold mt-6">2. No Guarantee of Uniqueness</h2>
            <p className="text-lg">
              While we aim to generate unique and creative names, we cannot guarantee that any generated name is original or unused elsewhere. It is your responsibility to verify name usage before applying it to any commercial product, trademark, or public work.
            </p>
            
            <h2 className="text-2xl font-semibold mt-6">3. AI-Generated Content</h2>
            <p className="text-lg">
              All content on this site, including names and descriptions, is generated using AI based on curated prompts. The creators of Fantasy Name Creator are not liable for any unintended, offensive, or inaccurate output produced by the generator.
            </p>
            
            <h2 className="text-2xl font-semibold mt-6">4. Privacy</h2>
            <p className="text-lg">
              We do not collect personal data. Basic anonymous analytics may be used to help improve the site. For more information, please review our{' '}
              <Link to="/privacy" className="text-blue-400 underline">
                Privacy Policy
              </Link>.
            </p>
            
            <h2 className="text-2xl font-semibold mt-6">5. Changes to Terms</h2>
            <p className="text-lg">
              We may update these Terms of Use at any time without prior notice. Continued use of Fantasy Name Creator after changes are published indicates your acceptance of the updated terms.
            </p>
            
            <p className="text-lg">
              If you have any questions or concerns, please{' '}
              <Link to="/contact" className="text-blue-400 underline">
                contact us
              </Link> or visit{' '}
              <a
                href="https://neoantica.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-400 underline"
              >
                Neoantica.com
              </a>.
            </p>

      </div>

      <Link
        to="/"
        className="mt-10 inline-block bg-indigo-700 hover:bg-indigo-600 text-white font-semibold py-2 px-6 rounded-lg transition"
      >
        ← Back to Fantasy Name Creator
      </Link>
        </main>
       <Footer />
     </div>
  );
}
