import React from 'react';
import { Link } from 'react-router-dom';
import Footer from '../components/Footer';

export default function Terms() {
  return (
    <div className="min-h-screen flex flex-col items-center">
      <header className="w-full text-center pt-10 pb-6 px-4 bg-gradient-to-b from-fantasy-dark-secondary to-fantasy-dark border-b border-white/5">
        <Link to="/" onClick={() => window.scrollTo(0, 0)} className="text-fantasy-gold hover:text-white transition font-fantasy text-xl mb-2 inline-block relative z-50">
          ← Back to Home
        </Link>
        <h1 className="text-4xl md:text-5xl font-bold text-transparent bg-clip-text bg-gold-gradient drop-shadow-sm tracking-wide">
          Terms of Use
        </h1>
      </header>

      <main className="w-full max-w-4xl mx-auto px-6 py-12 flex flex-col items-center flex-grow">
        <div className="prose prose-invert prose-lg max-w-none text-gray-300">
          <p>
            Welcome to <strong>Fantasy Name Creator</strong>, a free fantasy name generation tool provided by Neoantica. By using this website, you agree to the following terms and conditions. If you do not agree with these terms, please do not use the site.
          </p>

          <h2 className="text-fantasy-gold font-fantasy">1. Use of the Service</h2>
          <p>
            Fantasy Name Creator is intended for creative purposes such as worldbuilding, storytelling, TTRPG design, writing, or personal projects. You may freely use the names generated by this tool. For commercial use, attribution to Fantasy Name Creator or Neoantica is appreciated but not required.
          </p>

          <h2 className="text-fantasy-gold font-fantasy">2. No Guarantee of Uniqueness</h2>
          <p>
            While we aim to generate unique and creative names, we cannot guarantee that any generated name is original or unused elsewhere. It is your responsibility to verify name usage before applying it to any commercial product, trademark, or public work.
          </p>

          <h2 className="text-fantasy-gold font-fantasy">3. AI-Generated Content</h2>
          <p>
            All content on this site, including names and descriptions, is generated using AI based on curated prompts. The creators of Fantasy Name Creator are not liable for any unintended, offensive, or inaccurate output produced by the generator.
          </p>

          <h2 className="text-fantasy-gold font-fantasy">4. Privacy</h2>
          <p>
            We do not collect personal data. Basic anonymous analytics may be used to help improve the site. For more information, please review our{' '}
            <Link to="/privacy" onClick={() => window.scrollTo(0, 0)} className="text-fantasy-gold hover:text-white transition underline decoration-dotted">
              Privacy Policy
            </Link>.
          </p>

          <h2 className="text-fantasy-gold font-fantasy">5. Changes to Terms</h2>
          <p>
            We may update these Terms of Use at any time without prior notice. Continued use of Fantasy Name Creator after changes are published indicates your acceptance of the updated terms.
          </p>

          <p>
            If you have any questions or concerns, please{' '}
            <Link to="/contact" onClick={() => window.scrollTo(0, 0)} className="text-fantasy-gold hover:text-white transition underline decoration-dotted">
              contact us
            </Link> or visit{' '}
            <a href="https://neoantica.com" target="_blank" rel="noopener noreferrer" className="text-fantasy-gold hover:text-white transition underline decoration-dotted">
              Neoantica.com
            </a>.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
